### ISSUE TITLE
How can i add more KEYs?

### ISSUE THREAD

**Issue by zzusec** [namoscato/action-tinify#276]
Can i apply more than 10 KEY with Batch compress? How can i do it ?

**Comment by namoscato** [comment]
@zzusec, I'm not sure I follow. Are you needing to configure multiple Tinify API keys?

**Comment by zzusec** [comment]
Yes，I have more than 10000 pictures to compress. ---- Replied Message ----FromNick ***@***.***>Date09/17/2021 19:53 ***@***.***> ***@***.******@***.***>SubjectRe: [namoscato/action-tinify] How can i add more KEYs? (#276)
@zzusec, I'm not sure I follow. Are you needing to configure multiple Tinify API keys?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/namoscato/action-tinify/issues/276#issuecomment-921736561",
"url": "https://github.com/namoscato/action-tinify/issues/276#issuecomment-921736561",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by namoscato** [comment]
You need to upgrade to a paid [Tinify API plan](https://tinify.com/dashboard/api).
